### ISSUE TITLE
Exception in thread Thread-58

### ISSUE THREAD

**Issue by thejohnd0e** [NON906/sd-webui-chatgpt#12]
![Screenshot - 2024-03-28 09 23 57](https://github.com/NON906/sd-webui-chatgpt/assets/115493464/55e07356-b13e-4050-a778-6234dce59754)

**Comment by NON906** [comment]
I pushed ce8cce48236d5e6f4fd70787ff654948a6832a70.
If the version of openai is different, it will be reinstalled.
Please check if this works correctly.

**Comment by thejohnd0e** [comment]
> I pushed [ce8cce4](https://github.com/NON906/sd-webui-chatgpt/commit/ce8cce48236d5e6f4fd70787ff654948a6832a70). If the version of openai is different, it will be reinstalled. Please check if this works correctly.

![Screenshot - 2024-04-03 00 42 58](https://github.com/NON906/sd-webui-chatgpt/assets/115493464/9a82cc16-e1d5-4067-9401-653af514e11d)

**Comment by NON906** [comment]
I fixed with 203cfed8904259c630b4195225adcee3c5516155.
Please try it.

**Comment by NON906** [comment]
What will happen if you change the relevant part as below?

(D:\stable-diffusion-main\extensions\sd-webui-chatgpt\scripts\main.py Line: 547)

```py
                fn=lambda t, c: ['', c + [(t, None)]], 
```

to

```py
                fn=lambda t, c: ['', c + [(t, None)] if c is not None else [(t, None)]],
```

**Comment by thejohnd0e** [comment]
> What will happen if you change the relevant part as below?
> 
> (D:\stable-diffusion-main\extensions\sd-webui-chatgpt\scripts\main.py Line: 547)
> 
> ```python
>                 fn=lambda t, c: ['', c + [(t, None)]], 
> ```
> 
> to
> 
> ```python
>                 fn=lambda t, c: ['', c + [(t, None)] if c is not None else [(t, None)]],
> ```


![Screenshot - 2024-04-03 15 45 25](https://github.com/NON906/sd-webui-chatgpt/assets/115493464/9237c63b-8b18-45f3-b33d-05ead8596dc8)

I did,  SD doesn't start

**Comment by NON906** [comment]
Thank you for checking.
I reflect it (eac8d21ea35cefe01856147d824a9aad95df8aa8) and closed this issue.
